__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/dfine_r50vd.yml',
]


output_dir: ./output/dfine_hgnetv2_b4_6x_coco


DFINE:
  backbone: HGNetv2


HGNetv2:
  name: 'B4'
  return_idx: [1, 2, 3]
  freeze_stem_only: True
  freeze_at: 0
  freeze_norm: True

DFINETransformer:
  num_layers: 6
  eval_idx: -1

HybridEncoder:
  depth_mult: 1.0
  expansion: 1.0
  
optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0002
  betas: [0.9, 0.999]
  weight_decay: 0.0001

epoches: 100


train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: 72
  collate_fn:
    scales: [480, 512, 544, 576, 608, 640, 640, 672, 704, 736, 768, 800]
    stop_epoch: 72