__include__: [
  '../dataset/obj365_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer_obj365.yml',
  './include/dfine_r50vd.yml',
]

output_dir: ./output/dfine_hgnetv2_b4_3x_obj365


DFINE:
  backbone: HGNetv2


HGNetv2:
  name: 'B4'
  return_idx: [1, 2, 3]
  freeze_stem_only: True
  freeze_at: 0
  freeze_norm: True

DFINETransformer:
  num_layers: 6
  eval_idx: -1

HybridEncoder:
  depth_mult: 1.0
  expansion: 1.0
  
optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00004
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0008
  betas: [0.9, 0.999]
  weight_decay: 0.000025

epoches: 36

train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: 37
  collate_fn:
    stop_epoch: 37