__include__: [
  '../../dataset/coco_detection.yml',
  '../../runtime.yml',
  '../include/dataloader.yml',
  '../include/optimizer.yml',
  '../include/dfine_hgnetv2.yml',
]


output_dir: ../../../output/dfine_hgnetv2_m_2x_obj2coco


DFINE:
  backbone: HGNetv2


HGNetv2:
  name: 'B2'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True

DFINETransformer:
  num_layers: 4
  eval_idx: -1

HybridEncoder:
  in_channels: [384, 768, 1536]
  hidden_dim: 256
  depth_mult: 0.67

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00001
    - 
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.00001
      weight_decay: 0.
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

epoches: 50

DFINECriterion:
  end_epoch: 36

train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: 36
  collate_fn:
    stop_epoch: 36
    ema_restart_decay: 0.9999
    scale_ori_repeat: 6

ema:
  warmups: 0

DFINECriterion:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2, loss_dfl: 0.1, loss_local: 1.0}
  
lr_warmup_scheduler:
  warmup_duration: 0